version: "3.1"
services:
  postgresql:
    image: quay.io/redhatdemo/openshift-pgsql12-centos8
    ports:
      - "5432:5432"
    environment:
      PG_USER_PASSWORD: password!
      PG_USER_NAME: demo
      PG_DATABASE: gamedb
      PG_NETWORK_MASK: all
