apiVersion: v1
kind: Service
metadata:
  name: postgresql
spec:
  selector:
    app: postgresql
  ports:
  - port: 5432
    targetPort: 5432
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql
spec:
  selector:
    matchLabels:
      app: postgresql
  template:
    metadata:
      labels:
        app: postgresql
    spec:
      securityContext:
        fsGroup: 26
      containers:
      - name: postgresql
        image: registry.access.redhat.com/rhscl/postgresql-96-rhel7
        imagePullPolicy: IfNotPresent
        env:
        -  name: "POSTGRESQL_PASSWORD"
           value: "password!"
        -  name: "POSTGRESQL_USER"
           value: "demo"
        -  name: "POSTGRESQL_DATABASE"
           value: "demodb"
        livenessProbe:
          exec:
            command:
            - /usr/libexec/check-container
            - --live
          initialDelaySeconds: 120
          timeoutSeconds: 10
        readinessProbe:
            exec:
              command:
              - /usr/libexec/check-container
            initialDelaySeconds: 5
            timeoutSeconds: 1
        resources:
          limits:
            memory: "512Mi"   
        volumeMounts:
          - mountPath: /var/lib/pgsql/data
            name: postgresql-data
      volumes:
        - name: postgresql-data          
          persistentVolumeClaim:
              claimName: postgresql-data
