version: "3.7"
services:
  messaging:
    image: quay.io/redhatdemo/2020-leaderboard-messaging
    ports:
      - "8080:8080"
    environment:
      PG_USER_PASSWORD: password!
      PG_USER_NAME: demo
      PG_DATABASE: gamedb
      PG_NETWORK_MASK: all
      PG_MAX_CONNECTIONS: 100
      PG_SHARED_BUFFERS: 256
      PG_WORK_MEM: 1536
      PG_EFFECTIVE_CACHE_SIZE: 1
      PG_EFFECTIVE_IO: 128
      PG_MAX_WAL_SIZE: 1
    volumes:
      - type: bind
        source: ../pgdata
        target: /pgdata
